baseURL = "https://www.adubhlaoich.ie"
languageCode = "en-IE"
title = "ADubhlaoich"

[permalinks]
    blog = "/:filename/"

[menu]
    [[menu.main]]
        name = "Home"
        pre = "home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Writing"
        pre = "edit"
        url = "/blog/"
        weight = 2
    [[menu.main]]
        name = "Topics"
        pre = "topic"
        url = "/topics/"
        weight = 3

[params]
    dateFormat = "January 2, 2006"
    homeText = "Test commit push. Has the navigation bar moved?"

[taxonomies]
    topic = "topics"